### ISSUE TITLE
4L 회고 / 23.10.25 / Day86 🐧🐳💪

### ISSUE THREAD

**Issue by aaingyunii** [aaingyunii/Bootcamp_TIL#86]
## Liked
- `nginx-proxy` repo를 통해 학습하면서 **`LOAD BALANCING`** 에 대한 이해가 되었고 `docker` 사용에 익숙해지는 과정이 만족스러웠습니다.

- 다양한 deploy 과정을 하면서 이에 익숙해질 수 있었고 더 이상 `localhost` 접속이 아닌 주소값으로 만든 사이트들에 접근할 수 있게 되어 만족스러웠습니다.

## Lacked
- 포트폴리오 사이트가 미완성이여서 검색엔진 최적화 하기에 부족해서 아쉬웠습니다.

## Learned
- [SEO 검색엔진 최적화](https://github.com/dj-twenty-six/101/issues/19) 를 통해 이전에 만든 개인 블로그(github.io) 페이지의 검색 노출을 설정을 하는 것을 진행하는 것으로 시작했습니다.

    - 네이버, 구글 각각으로부터 검색 사이트 등록하는 것을 진행했고,
    - 네이버의 "사이트 간단체크" 를 통해 웹 페이지 최적화 정보를 조회하는 등의 활동을 진행했습니다.

- ### [aai-API](https://github.com/aaingyunii/aai-API)

    1.  `pypi.org` 에 배포했던 pip 들을 설치해 `FastAPI` 모듈을 통해 웹 API 테스트를 하고
    2.  `Dockerfile` 로 실행 및 테스트를 마친 후
    3. `fly.io` 로 배포
    4. 이전에 빌드한 도커 이미지를 docker-hub에 배포까지 완료했습니다.
    - https://aai-api.fly.dev/
    - https://hub.docker.com/r/aaingyunii/aai-api/tags

- ### [nginx-proxy](https://github.com/aaingyunii/nginx-proxy) 

: `compose.yml` 을 이용해 `docker compose` 로 `nginx` 컨테이너-proxy 서버를 만들고 이로부터 파생된 `whoami` 서버를 만드는 작업을 수행했습니다. 또한 compose.yml 파일을 수정하면서 `Scale out-in / up-down` => `load balancing` 의 작업을 수행했습니다. 
아래 명령어와 compose.yml 수정을 통해 진행했습니다.

```bash
$ docker compose up -d # compose.yml 의 따라 이미지와 컨테이너를 생성하고 활성화

$ docker compose  ps # 현재 실행 중인 컨테이너 리스트 확인

$ docker compose up -d --scale whoami=3 # scale out-in 관련 명령어
                                        # --scale {서버명}=n, n개 만큼의 서버를 늘리거나 줄임

$ docker stats # 실행 중인 컨테이너의 
                       # CPU %  ,MEM USAGE / LIMIT ,MEM %  정보를 실시간으로 확인
```

- compose.yml
```
version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    deploy:
      resources:
        limits:
          cpus: '0.20' # scale up-down 관련 조정 변수
          memory: 77M # scale up-down 관련 조정 변수
        reservations:
          cpus: '0.01'
          memory: 30M

  whoami:
    image: jwilder/whoami
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=whoami.example
      - VIRTUAL_PORT=8000
    deploy:
      mode: replicated
      replicas: 2 # https://docs.docker.com/compose/compose-file/deploy/#replicas
      resources:  # https://docs.docker.com/compose/compose-file/compose-file-v3/#resources
        limits:
          cpus: '0.05' # scale up-down 관련 조정 변수
          memory: 33M # scale up-down 관련 조정 변수
        reservations:
          cpus: '0.01'
          memory: 6M
```
## Longed for
- 취업 준비 및 복습
